version: '3'
services:
  kong-api-gateway:
    container_name: sb_kong-api-gateway
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"

  zookeeper:
    container_name: sb_zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: sb_kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,PLAINTEXT://kafka:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  product-service-app:
    container_name: sb_product-service-app
    build:
      # build from Dockerfile
      context: product-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  user-service-app:
    container_name: sb_user-service-app
    build:
      # build from Dockerfile
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  order-service-app:
    container_name: sb_order-service-app
    build:
      # build from Dockerfile
      context: order-service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  checkout-service-app:
    container_name: sb_checkout-service-app
    build:
      # build from Dockerfile
      context: checkout-service
      dockerfile: Dockerfile
    ports:
      - "9004:9004"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  email-service-app:
    container_name: sb_email-service-app
    build:
      # build from Dockerfile
      context: email-service
      dockerfile: Dockerfile
    ports:
      - "9005:9005"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  payment-service-app:
    container_name: sb_payment-service-app
    build:
      # build from Dockerfile
      context: payment-service
      dockerfile: Dockerfile
    ports:
      - "9006:9006"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  cart-service-app:
    container_name: sb_cart-service-app
    build:
      # build from Dockerfile
      context: cart-service
      dockerfile: Dockerfile
    ports:
      - "9007:9007"
    links:
      - postgres-db
      - kafka
    depends_on:
      - kafka
      - postgres-db

  postgres-db:
    container_name: sb_general-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome1
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local