version: '3'
services:
  kong-api-gateway:
    container_name: kong-api-gateway
    image: kong:latest
    volumes:
      - ./apigateway/kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      -
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  product-service-app:
    container_name: product-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "9001:9001"
    links:
      - postgres-db

  user-service-app:
    container_name: user-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "9002:9002"
    links:
      - postgres-db

  order-service-app:
    container_name: order-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "9003:9003"
    links:
      - postgres-db

  checkout-service-app:
    container_name: checkout-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./checkout-service/Dockerfile
    ports:
      - "9004:9004"
    links:
      - postgres-db

  email-service-app:
    container_name: email-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./email-service/Dockerfile
    ports:
      - "9005:9005"
    links:
      - postgres-db

  payment-service-app:
    container_name: payment-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./payment-service/Dockerfile
    ports:
      - "9006:9006"
    links:
      - postgres-db

  cart-service-app:
    container_name: cart-service-app
    build:
      # build from Dockerfile
      context: .
      dockerfile: ./cart-service/Dockerfile
    ports:
      - "9007:9007"
    links:
      - postgres-db

  postgres-db:
    container_name: general-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome1
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local