version: '3.8'
services:
  kong-api-gateway:
    container_name: jolie_kong-api-gateway
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"

  product-service-app:
    container_name: jolie_product-service-app
    build:
    # build from Dockerfile
      context: product-service
      dockerfile: Dockerfile
    ports:
      - "9051:9051"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db   

  user-service-app:
    container_name: jolie_user-service-app
    build:
    # build from Dockerfile
      context: user-service
      dockerfile: Dockerfile
    ports:
      - "9052:9052"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db 

  order-service-app:
    container_name: jolie_order-service-app
    build:
    # build from Dockerfile
      context: order-service
      dockerfile: Dockerfile
    ports:
      - "9053:9053"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db 

  checkout-service-app:
    container_name: jolie_checkout-service-app
    build:
    # build from Dockerfile
      context: checkout-service
      dockerfile: Dockerfile
    ports:
      - "9054:9054"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db 

  email-service-app:
    container_name: jolie_email-service-app
    build:
    # build from Dockerfile
      context: email-service
      dockerfile: Dockerfile
    ports:
      - "9055:9055"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db 

  payment-service-app:
    container_name: jolie_payment-service-app
    build:
    # build from Dockerfile
      context: payment-service
      dockerfile: Dockerfile
    ports:
      - "9056:9056"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db  

  cart-service-app:
    container_name: jolie_cart-service-app
    build:
    # build from Dockerfile
      context: cart-service
      dockerfile: Dockerfile
    ports:
      - "9057:9057"
    # volumes:
    #   - "./:/app"
    links:
      - postgres-db
    depends_on:
      - postgres-db  
      
  postgres-db:
    container_name: jolie_general-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome1
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local